const jobs=[
 {title:'Software Engineering Intern',company:'Razorpay',logo:'R',bg:'#dce5fb',match:96,meta:['Bengaluru','Starts Jun 2026'],skills:['React','Node.js','TypeScript'],stipend:'₹35,000 / mo',paid:true},
 {title:'Product Design Intern',company:'Meesho',logo:'m',bg:'#ffe8e5',match:92,meta:['Bengaluru','Starts May 2026'],skills:['Figma','UX Research','Prototyping'],stipend:'₹30,000 / mo',paid:true},
 {title:'Data Science Intern',company:'Swiggy',logo:'S',bg:'#fff1d1',match:89,meta:['Bengaluru','Starts Jun 2026'],skills:['Python','SQL','Machine Learning'],stipend:'₹25,000 / mo',paid:true},
 {title:'Frontend Developer Intern',company:'CRED',logo:'C',bg:'#202020',match:86,meta:['Remote','Starts May 2026'],skills:['React','CSS','JavaScript'],stipend:'₹20,000 / mo',paid:true},
 {title:'AI Research Intern',company:'Sarvam AI',logo:'S',bg:'#dbf0e5',match:83,meta:['Bengaluru','Starts Jul 2026'],skills:['Python','LLMs','PyTorch'],stipend:'Certificate',paid:false},
 {title:'Cloud Engineering Intern',company:'Nutanix',logo:'N',bg:'#e6e1fb',match:79,meta:['Bengaluru','Starts Jun 2026'],skills:['AWS','Docker','Linux'],stipend:'₹28,000 / mo',paid:true}
];
const cards=document.querySelector('#cards'), tabs=document.querySelectorAll('.tab');let active='all';
function render(){const term=document.querySelector('#search').value.toLowerCase();const filtered=jobs.filter(j=>(active==='all'||(active==='paid')===j.paid)&&`${j.title} ${j.company} ${j.skills.join(' ')}`.toLowerCase().includes(term));cards.innerHTML=filtered.map(j=>`<article class="job-card"><div class="job-top"><div class="company-logo" style="background:${j.bg};color:${j.bg==='#202020'?'#fff':'#263d34'}">${j.logo}</div><span class="match">${j.match}% match</span></div><h3>${j.title}</h3><p class="company">${j.company}</p><div class="meta"><span>⌖ ${j.meta[0]}</span><span>◷ ${j.meta[1]}</span></div><div class="tags">${j.skills.map(s=>`<span>${s}</span>`).join('')}</div><div class="job-footer"><span class="stipend">${j.stipend}</span><span class="paid-label">${j.paid?'PAID':'UNPAID'}</span></div></article>`).join('');document.querySelector('#match-count').textContent=filtered.length?14:0}
tabs.forEach(t=>t.addEventListener('click',()=>{tabs.forEach(x=>x.classList.remove('active'));t.classList.add('active');active=t.dataset.tab;render()}));document.querySelector('#search').addEventListener('input',render);document.querySelector('#find-btn').addEventListener('click',render);
document.querySelector('#resume-upload').addEventListener('change',e=>{if(e.target.files[0])document.querySelector('#resume-name').textContent=e.target.files[0].name});
const modal=document.querySelector('#modal');document.querySelector('#analyze-btn').addEventListener('click',()=>{document.querySelector('#company-name').textContent=document.querySelector('#company-input').value||'your dream company';modal.classList.add('open')});document.querySelector('#close-modal').addEventListener('click',()=>modal.classList.remove('open'));document.querySelector('#modal-done').addEventListener('click',()=>modal.classList.remove('open'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});
render();
